export interface Certificate {
  title: string;
  subtitle: string;
  description: string;
  link: string;
  image: string;
}

export interface Projects {
  title: string;
  viewProject: string;
  viewCode: string;
  viewDemo: string;
  items: ProjectItem[];
}

export interface ProjectItem {
  title: string;
  description: string;
  imageFolder: string;
  imageCount: number;
  images?: string[]; // Generated by store
  url: string;
  repo: string;
  demo?: string;
  technologies: Technology[];
  status?: string;
  privateProject?: boolean;
}
export interface Section {
  id: number;
  name: string;
  url: string;
}

export interface Contact {
  title: string;
  contactForm: ContactField[];
}

export interface ContactField {
  id: string;
  label: string;
  placeholder: string;
  type: string;
  required: boolean;
}

export interface Presentation {
  hello: string;
  name: string;
  alias: string;
  webdeveloper: string;
}

export interface ProfessionalSkill {
  title: string;
  description: string;
  icon: string;
  color: string;
}

export interface About {
  title: string;
  intro?: string;
  description: string;
  highlights: string[];
  professional_skills: ProfessionalSkill[];
}

export interface Technology {
  title: string;
  icon: string;
  color: string;
}

export interface ExperienceItem {
  year: string;
  company: string;
  position: string;
  type: string;
  description: string;
  technologies: string[];
  achievements: string[];
  status?: string;
}

export interface Experience {
  title: string;
  items: ExperienceItem[];
}

export interface Content {
  presentation: Presentation;
  about: About;
  certificates: Certificate[];
  experience: Experience;
  projects: Projects;
  contact: Contact;
  sections: Section[];
  skills: {
    title: string;
    items: Technology[];
  };
  settings: {
    darkmode: string;
    lightmode: string;
    english: string;
    spanish: string;
  };
}

export interface Language {
  id: number;
  name: string;
  code: string;
  icon: string;
  content: Content;
  cv: string;
}
